//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Business.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyApp.Business.Resource.EmailResource", typeof(EmailResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear ##firstname## ##surname##, &lt;br/&gt;&lt;br/&gt;
        ///&apos;##emailaddress##&apos;.
        /// </summary>
        public static string accouncreationbody {
            get {
                return ResourceManager.GetString("accouncreationbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation of account creation.
        /// </summary>
        public static string accouncreationsubject {
            get {
                return ResourceManager.GetString("accouncreationsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;#ffffff&quot; style=&quot;margin: 30px;font-family: Verdana, Arial, Verdana, Sans-Serif;&quot; &gt;
        ///    &lt;!--STARTTEMPLATE--&gt;
        ///    &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellpadding=&quot;3&quot; cellspacing=&quot;3&quot; style=&quot;max-width:960px;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td height=&quot;60&quot; colspan=&quot;3&quot; valign=&quot;top&quot; style=&quot;font-size: 12p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string baseemailtemplate {
            get {
                return ResourceManager.GetString("baseemailtemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Registrant,&lt;br/&gt;&lt;br/&gt;
        ///
        ///Thank you for creating your account. Please click on the link in the body of the email to verify your account and continue with your registration.&lt;br/&gt;&lt;br/&gt;
        ///
        ///&lt;a href=&quot;##LINK##&quot;&gt;Verify my account&lt;/a&gt;&lt;br/&gt;.
        /// </summary>
        public static string confirmaccountemailbody {
            get {
                return ResourceManager.GetString("confirmaccountemailbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Verification.
        /// </summary>
        public static string confirmaccountemailsubject {
            get {
                return ResourceManager.GetString("confirmaccountemailsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear ##firstname## ##surname##,
        ///.
        /// </summary>
        public static string ConfirmDetailsCorrect {
            get {
                return ResourceManager.GetString("ConfirmDetailsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation of details.
        /// </summary>
        public static string ConfirmDetailsCorrectSubject {
            get {
                return ResourceManager.GetString("ConfirmDetailsCorrectSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, .
        /// </summary>
        public static string createsyatemaccountsendwelcomemeial {
            get {
                return ResourceManager.GetString("createsyatemaccountsendwelcomemeial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;&lt;br/&gt;Please note. This email was sent to you automatically, so please do not reply..
        /// </summary>
        public static string emailfooter {
            get {
                return ResourceManager.GetString("emailfooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear ##firstname## ##surname##, &lt;br/&gt;&lt;br/&gt;
        ///Your temporary password is &lt;strong&gt;{0}&lt;/strong&gt;.&lt;br/&gt;&lt;br/&gt;
        ///Please follow this link to &lt;a href=&quot;##LINK##&quot;&gt;reset your password&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///Kind Regards,&lt;br/&gt;
        ///My App&lt;br/&gt;&lt;br/&gt;.
        /// </summary>
        public static string passwordresetbody {
            get {
                return ResourceManager.GetString("passwordresetbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase Reset.
        /// </summary>
        public static string passwordresetsubject {
            get {
                return ResourceManager.GetString("passwordresetsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@xxxxx.com.
        /// </summary>
        public static string standardemaiaddress {
            get {
                return ResourceManager.GetString("standardemaiaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Created.
        /// </summary>
        public static string systemaccountcreatedsubject {
            get {
                return ResourceManager.GetString("systemaccountcreatedsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear ##firstname## ##surname##, &lt;br/&gt;&lt;br/&gt;
        ///&apos;##emailaddress##&apos;.&lt;br/&gt;&lt;br/&gt;
        ///Kind Regards&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;.
        /// </summary>
        public static string welcomepackbody {
            get {
                return ResourceManager.GetString("welcomepackbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject here.
        /// </summary>
        public static string WelcomepackSubject {
            get {
                return ResourceManager.GetString("WelcomepackSubject", resourceCulture);
            }
        }
    }
}
